---
- name: Rebuild Sendmail configuration
  ansible.builtin.shell: make && make install
  args:
    chdir: /etc/mail

- name: Rebuild aliases.db
  ansible.builtin.command: newaliases

- name: Start Sendmail
  ansible.builtin.service:
    name: sendmail
    state: started

- name: Stop Sendmail
  ansible.builtin.service:
    name: sendmail
    state: stopped
